<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rappix.BuildingBlocks.Imaging</RootNamespace>
    <AssemblyName>Rappix.BuildingBlocks.Imaging</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rappix.BuildingBlocks.Core\Rappix.BuildingBlocks.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
