<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rappix.BuildingBlocks.Storage</RootNamespace>
    <AssemblyName>Rappix.BuildingBlocks.Storage</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rappix.BuildingBlocks.Core\Rappix.BuildingBlocks.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Minio" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
