<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rappix.Dispatch.Infrastructure</RootNamespace>
    <AssemblyName>Rappix.Dispatch.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Permite a las pruebas instanciar repositorios y consumers internos. -->
    <InternalsVisibleTo Include="Rappix.Dispatch.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <!-- Cache distribuida para idempotencia REST + cliente Redis para Geo matching de couriers. -->
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rappix.Dispatch.Application\Rappix.Dispatch.Application.csproj" />
    <ProjectReference Include="..\Rappix.Dispatch.Domain\Rappix.Dispatch.Domain.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Rappix.Contracts\Rappix.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Rappix.BuildingBlocks.Core\Rappix.BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Rappix.BuildingBlocks.Messaging\Rappix.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
